### EmailExists
GRPC localhost:5050/FL.v1.Auth/EmailExists

{
  "email": "petr@example.com"
}

### Register
GRPC localhost:5050/FL.v1.Auth/Register

{
  "email": "petr@example.com",
  "password": "SuperSecret123"
}

### Login
GRPC localhost:5050/FL.v1.Auth/Login

{
  "email": "petr@example.com",
  "password": "SuperSecret123"
}
