// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/group.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Groups_CreateGroup_FullMethodName  = "/FL.v1.Groups/CreateGroup"
	Groups_ListMyGroups_FullMethodName = "/FL.v1.Groups/ListMyGroups"
	Groups_GetGroup_FullMethodName     = "/FL.v1.Groups/GetGroup"
	Groups_RenameGroup_FullMethodName  = "/FL.v1.Groups/RenameGroup"
	Groups_ListMembers_FullMethodName  = "/FL.v1.Groups/ListMembers"
	Groups_GetMyIncome_FullMethodName  = "/FL.v1.Groups/GetMyIncome"
	Groups_SetMyIncome_FullMethodName  = "/FL.v1.Groups/SetMyIncome"
	Groups_CreateInvite_FullMethodName = "/FL.v1.Groups/CreateInvite"
	Groups_AcceptInvite_FullMethodName = "/FL.v1.Groups/AcceptInvite"
)

// GroupsClient is the client API for Groups service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Идентификатор текущего пользователя во всех методах берётся из access-токена
// (заголовок gRPC-метаданных authorization: Bearer <access>), а не из тела запроса.
type GroupsClient interface {
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	ListMyGroups(ctx context.Context, in *ListMyGroupsRequest, opts ...grpc.CallOption) (*ListMyGroupsResponse, error)
	GetGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*Group, error)
	RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*RenameGroupResponse, error)
	ListMembers(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	GetMyIncome(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*IncomeResponse, error)
	SetMyIncome(ctx context.Context, in *SetMyIncomeRequest, opts ...grpc.CallOption) (*IncomeResponse, error)
	CreateInvite(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*InviteResponse, error)
	AcceptInvite(ctx context.Context, in *AcceptInviteRequest, opts ...grpc.CallOption) (*AcceptInviteResponse, error)
}

type groupsClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupsClient(cc grpc.ClientConnInterface) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, Groups_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ListMyGroups(ctx context.Context, in *ListMyGroupsRequest, opts ...grpc.CallOption) (*ListMyGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyGroupsResponse)
	err := c.cc.Invoke(ctx, Groups_ListMyGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) GetGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, Groups_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*RenameGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameGroupResponse)
	err := c.cc.Invoke(ctx, Groups_RenameGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ListMembers(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, Groups_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) GetMyIncome(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*IncomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomeResponse)
	err := c.cc.Invoke(ctx, Groups_GetMyIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) SetMyIncome(ctx context.Context, in *SetMyIncomeRequest, opts ...grpc.CallOption) (*IncomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomeResponse)
	err := c.cc.Invoke(ctx, Groups_SetMyIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) CreateInvite(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*InviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteResponse)
	err := c.cc.Invoke(ctx, Groups_CreateInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) AcceptInvite(ctx context.Context, in *AcceptInviteRequest, opts ...grpc.CallOption) (*AcceptInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptInviteResponse)
	err := c.cc.Invoke(ctx, Groups_AcceptInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsServer is the server API for Groups service.
// All implementations must embed UnimplementedGroupsServer
// for forward compatibility.
//
// Идентификатор текущего пользователя во всех методах берётся из access-токена
// (заголовок gRPC-метаданных authorization: Bearer <access>), а не из тела запроса.
type GroupsServer interface {
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	ListMyGroups(context.Context, *ListMyGroupsRequest) (*ListMyGroupsResponse, error)
	GetGroup(context.Context, *GroupIdRequest) (*Group, error)
	RenameGroup(context.Context, *RenameGroupRequest) (*RenameGroupResponse, error)
	ListMembers(context.Context, *GroupIdRequest) (*ListMembersResponse, error)
	GetMyIncome(context.Context, *GroupIdRequest) (*IncomeResponse, error)
	SetMyIncome(context.Context, *SetMyIncomeRequest) (*IncomeResponse, error)
	CreateInvite(context.Context, *GroupIdRequest) (*InviteResponse, error)
	AcceptInvite(context.Context, *AcceptInviteRequest) (*AcceptInviteResponse, error)
	mustEmbedUnimplementedGroupsServer()
}

// UnimplementedGroupsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupsServer struct{}

func (UnimplementedGroupsServer) CreateGroup(context.Context, *CreateGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupsServer) ListMyGroups(context.Context, *ListMyGroupsRequest) (*ListMyGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyGroups not implemented")
}
func (UnimplementedGroupsServer) GetGroup(context.Context, *GroupIdRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedGroupsServer) RenameGroup(context.Context, *RenameGroupRequest) (*RenameGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameGroup not implemented")
}
func (UnimplementedGroupsServer) ListMembers(context.Context, *GroupIdRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGroupsServer) GetMyIncome(context.Context, *GroupIdRequest) (*IncomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyIncome not implemented")
}
func (UnimplementedGroupsServer) SetMyIncome(context.Context, *SetMyIncomeRequest) (*IncomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMyIncome not implemented")
}
func (UnimplementedGroupsServer) CreateInvite(context.Context, *GroupIdRequest) (*InviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvite not implemented")
}
func (UnimplementedGroupsServer) AcceptInvite(context.Context, *AcceptInviteRequest) (*AcceptInviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptInvite not implemented")
}
func (UnimplementedGroupsServer) mustEmbedUnimplementedGroupsServer() {}
func (UnimplementedGroupsServer) testEmbeddedByValue()                {}

// UnsafeGroupsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupsServer will
// result in compilation errors.
type UnsafeGroupsServer interface {
	mustEmbedUnimplementedGroupsServer()
}

func RegisterGroupsServer(s grpc.ServiceRegistrar, srv GroupsServer) {
	// If the following call panics, it indicates UnimplementedGroupsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Groups_ServiceDesc, srv)
}

func _Groups_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ListMyGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ListMyGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_ListMyGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ListMyGroups(ctx, req.(*ListMyGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).GetGroup(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_RenameGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).RenameGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_RenameGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).RenameGroup(ctx, req.(*RenameGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ListMembers(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_GetMyIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).GetMyIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_GetMyIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).GetMyIncome(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_SetMyIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMyIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).SetMyIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_SetMyIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).SetMyIncome(ctx, req.(*SetMyIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_CreateInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).CreateInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_CreateInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).CreateInvite(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_AcceptInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).AcceptInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Groups_AcceptInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).AcceptInvite(ctx, req.(*AcceptInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Groups_ServiceDesc is the grpc.ServiceDesc for Groups service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Groups_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FL.v1.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _Groups_CreateGroup_Handler,
		},
		{
			MethodName: "ListMyGroups",
			Handler:    _Groups_ListMyGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _Groups_GetGroup_Handler,
		},
		{
			MethodName: "RenameGroup",
			Handler:    _Groups_RenameGroup_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _Groups_ListMembers_Handler,
		},
		{
			MethodName: "GetMyIncome",
			Handler:    _Groups_GetMyIncome_Handler,
		},
		{
			MethodName: "SetMyIncome",
			Handler:    _Groups_SetMyIncome_Handler,
		},
		{
			MethodName: "CreateInvite",
			Handler:    _Groups_CreateInvite_Handler,
		},
		{
			MethodName: "AcceptInvite",
			Handler:    _Groups_AcceptInvite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/group.proto",
}
