// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/group.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type GroupIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupIdRequest) Reset() {
	*x = GroupIdRequest{}
	mi := &file_proto_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupIdRequest) ProtoMessage() {}

func (x *GroupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupIdRequest.ProtoReflect.Descriptor instead.
func (*GroupIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupIdRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// name необязателен: если пуст, сервер назовёт группу "Группа {X+1}",
// где X — число групп, в которых уже состоит пользователь.
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMyGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyGroupsRequest) Reset() {
	*x = ListMyGroupsRequest{}
	mi := &file_proto_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyGroupsRequest) ProtoMessage() {}

func (x *ListMyGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListMyGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{3}
}

type ListMyGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyGroupsResponse) Reset() {
	*x = ListMyGroupsResponse{}
	mi := &file_proto_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyGroupsResponse) ProtoMessage() {}

func (x *ListMyGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListMyGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type RenameGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupRequest) Reset() {
	*x = RenameGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupRequest) ProtoMessage() {}

func (x *RenameGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupRequest.ProtoReflect.Descriptor instead.
func (*RenameGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{5}
}

func (x *RenameGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RenameGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupResponse) Reset() {
	*x = RenameGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupResponse) ProtoMessage() {}

func (x *RenameGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupResponse.ProtoReflect.Descriptor instead.
func (*RenameGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{6}
}

func (x *RenameGroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`       // пустая строка, если не задана
	MiddleName    string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"` // пустая строка, если не задано
	JoinedAt      string                 `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`       // RFC 3339, UTC
	Income        int64                  `protobuf:"varint,6,opt,name=income,proto3" json:"income,omitempty"`                          // в копейках
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`                               // owner | member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{7}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Member) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Member) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Member) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *Member) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_proto_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{8}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type SetMyIncomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Income        int64                  `protobuf:"varint,2,opt,name=income,proto3" json:"income,omitempty"` // в копейках, >= 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMyIncomeRequest) Reset() {
	*x = SetMyIncomeRequest{}
	mi := &file_proto_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMyIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMyIncomeRequest) ProtoMessage() {}

func (x *SetMyIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMyIncomeRequest.ProtoReflect.Descriptor instead.
func (*SetMyIncomeRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{9}
}

func (x *SetMyIncomeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetMyIncomeRequest) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

type IncomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Income        int64                  `protobuf:"varint,1,opt,name=income,proto3" json:"income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeResponse) Reset() {
	*x = IncomeResponse{}
	mi := &file_proto_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeResponse) ProtoMessage() {}

func (x *IncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeResponse.ProtoReflect.Descriptor instead.
func (*IncomeResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{10}
}

func (x *IncomeResponse) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

type InviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                            // 4 цифры
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC 3339, UTC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteResponse) Reset() {
	*x = InviteResponse{}
	mi := &file_proto_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResponse) ProtoMessage() {}

func (x *InviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResponse.ProtoReflect.Descriptor instead.
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{11}
}

func (x *InviteResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InviteResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type AcceptInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteRequest) Reset() {
	*x = AcceptInviteRequest{}
	mi := &file_proto_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteRequest) ProtoMessage() {}

func (x *AcceptInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptInviteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AcceptInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteResponse) Reset() {
	*x = AcceptInviteResponse{}
	mi := &file_proto_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteResponse) ProtoMessage() {}

func (x *AcceptInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteResponse.ProtoReflect.Descriptor instead.
func (*AcceptInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptInviteResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_proto_group_proto protoreflect.FileDescriptor

const file_proto_group_proto_rawDesc = "" +
	"\n" +
	"\x11proto/group.proto\x12\x05FL.v1\"U\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\"+\n" +
	"\x0eGroupIdRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"(\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListMyGroupsRequest\"<\n" +
	"\x14ListMyGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.FL.v1.GroupR\x06groups\"C\n" +
	"\x12RenameGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\")\n" +
	"\x13RenameGroupResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc7\x01\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\x12\x16\n" +
	"\x06income\x18\x06 \x01(\x03R\x06income\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\">\n" +
	"\x13ListMembersResponse\x12'\n" +
	"\amembers\x18\x01 \x03(\v2\r.FL.v1.MemberR\amembers\"G\n" +
	"\x12SetMyIncomeRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x03R\x06income\"(\n" +
	"\x0eIncomeResponse\x12\x16\n" +
	"\x06income\x18\x01 \x01(\x03R\x06income\"C\n" +
	"\x0eInviteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\")\n" +
	"\x13AcceptInviteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"1\n" +
	"\x14AcceptInviteResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId2\xc7\x04\n" +
	"\x06Groups\x126\n" +
	"\vCreateGroup\x12\x19.FL.v1.CreateGroupRequest\x1a\f.FL.v1.Group\x12G\n" +
	"\fListMyGroups\x12\x1a.FL.v1.ListMyGroupsRequest\x1a\x1b.FL.v1.ListMyGroupsResponse\x12/\n" +
	"\bGetGroup\x12\x15.FL.v1.GroupIdRequest\x1a\f.FL.v1.Group\x12D\n" +
	"\vRenameGroup\x12\x19.FL.v1.RenameGroupRequest\x1a\x1a.FL.v1.RenameGroupResponse\x12@\n" +
	"\vListMembers\x12\x15.FL.v1.GroupIdRequest\x1a\x1a.FL.v1.ListMembersResponse\x12;\n" +
	"\vGetMyIncome\x12\x15.FL.v1.GroupIdRequest\x1a\x15.FL.v1.IncomeResponse\x12?\n" +
	"\vSetMyIncome\x12\x19.FL.v1.SetMyIncomeRequest\x1a\x15.FL.v1.IncomeResponse\x12<\n" +
	"\fCreateInvite\x12\x15.FL.v1.GroupIdRequest\x1a\x15.FL.v1.InviteResponse\x12G\n" +
	"\fAcceptInvite\x12\x1a.FL.v1.AcceptInviteRequest\x1a\x1b.FL.v1.AcceptInviteResponseB-Z+github.com/mawi118/family_ledger_BACK/protob\x06proto3"

var (
	file_proto_group_proto_rawDescOnce sync.Once
	file_proto_group_proto_rawDescData []byte
)

func file_proto_group_proto_rawDescGZIP() []byte {
	file_proto_group_proto_rawDescOnce.Do(func() {
		file_proto_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_group_proto_rawDesc), len(file_proto_group_proto_rawDesc)))
	})
	return file_proto_group_proto_rawDescData
}

var file_proto_group_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_group_proto_goTypes = []any{
	(*Group)(nil),                // 0: FL.v1.Group
	(*GroupIdRequest)(nil),       // 1: FL.v1.GroupIdRequest
	(*CreateGroupRequest)(nil),   // 2: FL.v1.CreateGroupRequest
	(*ListMyGroupsRequest)(nil),  // 3: FL.v1.ListMyGroupsRequest
	(*ListMyGroupsResponse)(nil), // 4: FL.v1.ListMyGroupsResponse
	(*RenameGroupRequest)(nil),   // 5: FL.v1.RenameGroupRequest
	(*RenameGroupResponse)(nil),  // 6: FL.v1.RenameGroupResponse
	(*Member)(nil),               // 7: FL.v1.Member
	(*ListMembersResponse)(nil),  // 8: FL.v1.ListMembersResponse
	(*SetMyIncomeRequest)(nil),   // 9: FL.v1.SetMyIncomeRequest
	(*IncomeResponse)(nil),       // 10: FL.v1.IncomeResponse
	(*InviteResponse)(nil),       // 11: FL.v1.InviteResponse
	(*AcceptInviteRequest)(nil),  // 12: FL.v1.AcceptInviteRequest
	(*AcceptInviteResponse)(nil), // 13: FL.v1.AcceptInviteResponse
}
var file_proto_group_proto_depIdxs = []int32{
	0,  // 0: FL.v1.ListMyGroupsResponse.groups:type_name -> FL.v1.Group
	7,  // 1: FL.v1.ListMembersResponse.members:type_name -> FL.v1.Member
	2,  // 2: FL.v1.Groups.CreateGroup:input_type -> FL.v1.CreateGroupRequest
	3,  // 3: FL.v1.Groups.ListMyGroups:input_type -> FL.v1.ListMyGroupsRequest
	1,  // 4: FL.v1.Groups.GetGroup:input_type -> FL.v1.GroupIdRequest
	5,  // 5: FL.v1.Groups.RenameGroup:input_type -> FL.v1.RenameGroupRequest
	1,  // 6: FL.v1.Groups.ListMembers:input_type -> FL.v1.GroupIdRequest
	1,  // 7: FL.v1.Groups.GetMyIncome:input_type -> FL.v1.GroupIdRequest
	9,  // 8: FL.v1.Groups.SetMyIncome:input_type -> FL.v1.SetMyIncomeRequest
	1,  // 9: FL.v1.Groups.CreateInvite:input_type -> FL.v1.GroupIdRequest
	12, // 10: FL.v1.Groups.AcceptInvite:input_type -> FL.v1.AcceptInviteRequest
	0,  // 11: FL.v1.Groups.CreateGroup:output_type -> FL.v1.Group
	4,  // 12: FL.v1.Groups.ListMyGroups:output_type -> FL.v1.ListMyGroupsResponse
	0,  // 13: FL.v1.Groups.GetGroup:output_type -> FL.v1.Group
	6,  // 14: FL.v1.Groups.RenameGroup:output_type -> FL.v1.RenameGroupResponse
	8,  // 15: FL.v1.Groups.ListMembers:output_type -> FL.v1.ListMembersResponse
	10, // 16: FL.v1.Groups.GetMyIncome:output_type -> FL.v1.IncomeResponse
	10, // 17: FL.v1.Groups.SetMyIncome:output_type -> FL.v1.IncomeResponse
	11, // 18: FL.v1.Groups.CreateInvite:output_type -> FL.v1.InviteResponse
	13, // 19: FL.v1.Groups.AcceptInvite:output_type -> FL.v1.AcceptInviteResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_group_proto_init() }
func file_proto_group_proto_init() {
	if File_proto_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_group_proto_rawDesc), len(file_proto_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_group_proto_goTypes,
		DependencyIndexes: file_proto_group_proto_depIdxs,
		MessageInfos:      file_proto_group_proto_msgTypes,
	}.Build()
	File_proto_group_proto = out.File
	file_proto_group_proto_goTypes = nil
	file_proto_group_proto_depIdxs = nil
}
